### ISSUE TITLE
Crash Forge Server

### ISSUE THREAD

**Issue by paralolik** [SleepingTea98/Arcana#12]
Forge ver: 28.1.92
Mod ver: 0.0.2
[debug.log](https://github.com/SleepingTea98/Arcana/files/3882288/debug.log)
[latest.log](https://github.com/SleepingTea98/Arcana/files/3882289/latest.log)

just crash

**Comment by paralolik** [comment]
[crash-2019-11-23_13.58.00-server.txt](https://github.com/SleepingTea98/Arcana/files/3882302/crash-2019-11-23_13.58.00-server.txt)

**Comment by Crack3dC0d3** [comment]
Duplicate of #9
